server:
  undertow:
    worker-threads: 16
    direct-buffers: true
    buffer-size: 1024
spring:
  messages:
    basename: i18n/messages
  jackson:
    serialization:
      write-dates-as-timestamps: false
  data:
    rest:
      base-path: api
  datasource:
    url: ${jdbc.url}
    username: ${jdbc.username}
    password: ${jdbc.password}
  jpa:
    properties:
       hibernate:
         dialect: org.hibernate.dialect.MariaDBDialect
         connection:
           useUnicode: true
           characterEncoding: utf-8
           CharSet: utf-8
---
spring:
  profiles: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
---
spring:
  profiles: prod
  jpa:
    hibernate:
      ddl-auto: validate
